;; -*- Mode: Lisp; Package: Macsyma -*-

;; Maclisp compatibility definitions for the Lisp Machine.  This file
;; is for Lisp differences only.  No knowledge of Macsyma should be
;; contained in this file.

;; Couldn't this copy to some static area?
(DEFMACRO PURCOPY (X) X)

(DEFMACRO CHARPOS (IGNORE) '(CDR (CURSORPOS)))
(DEFMACRO SLEEP (SECONDS) `(PROCESS-SLEEP (FIX (* ,SECONDS 60.))))

(DEFUN LINEL (&OPTIONAL STREAM)
  (FUNCALL (SI:DECODE-PRINT-ARG STREAM) ':SIZE-IN-CHARACTERS))

;; Perhaps this should do something.
(DEFMACRO NOINTERRUPT (IGNORE) NIL)

(DEFMACRO FIXNUM-IDENTITY (X) X)
(DEFMACRO FLONUM-IDENTITY (X) X)

;; Keep the compiler quiet.
;; Use GET-PNAME or FORMAT instead of EXPLODE, EXPLODEN, EXPLODEC.
;; Use AREF instead of GETCHAR and GETCHARN.
;; Use MAKE-SYMBOL instead of MAKNAM.
;; Use INTERN instead of IMPLODE.
;; Use STRING-LESSP instead of ALPHALESSP.

(REMPROP 'EXPLODE       'COMPILER:STYLE-CHECKER)
(REMPROP 'EXPLODEC      'COMPILER:STYLE-CHECKER)
(REMPROP 'EXPLODEN      'COMPILER:STYLE-CHECKER)
(REMPROP 'ALPHALESSP    'COMPILER:STYLE-CHECKER)
(REMPROP 'GETCHARN      'COMPILER:STYLE-CHECKER)
(REMPROP 'GETCHAR       'COMPILER:STYLE-CHECKER)
(REMPROP 'IMPLODE       'COMPILER:STYLE-CHECKER)
(REMPROP 'MAKNAM        'COMPILER:STYLE-CHECKER)

(DEFMACRO WHEN (PRED &BODY BODY)
  `(COND (,PRED . ,BODY)))

(DEFMACRO UNLESS (PRED &BODY BODY)
  `(COND ((NOT ,PRED) . ,BODY)))

(DEFMACRO SFA-CALL (STREAM OPERATION ARG)
  `(FUNCALL ,STREAM (READ-FROM-STRING (STRING-APPEND #/: ,OPERATION)) ,ARG))

;; Things that appear within DECLARE bodies.

;; Why doesn't this work?
;; Because of the brain-damaged way the lispm compiler is written. -gjc
;; (PUTPROP 'DECLARE '(DECLARE-OPTIMIZER) 'COMPILER:OPTIMIZERS)
;;
;; (DEFUN DECLARE-OPTIMIZER (DECLARE-FORM &AUX (RETURN-FORM NIL))
;;   (DO ((L (REVERSE (CDR DECLARE-FORM)) (CDR L)))
;;       ((NULL L))
;;     (IF (NOT (MEMQ (CAAR L)
;; 		   '(FIXNUM FLONUM NOTYPE MACROS ARRAY* GENPREFIX
;; 			    CLOSED MUZZLED MAPEX SPLITFILE)))
;; 	(PUSH (CAR L) RETURN-FORM)))
;;   (IF RETURN-FORM (CONS 'DECLARE RETURN-FORM) NIL))

;; These are in global, so avoid redefinition warning by using FDEFINE
;; rather than DEFUN.
(FDEFINE 'FLONUM #'(LAMBDA (&QUOTE &REST IGNORE) NIL))
(FDEFINE 'ARGS	 #'(LAMBDA (&QUOTE &REST IGNORE) NIL))

(DEFUN MACROS	     (&QUOTE &REST IGNORE) NIL)
(DEFUN CLOSED	     (&QUOTE &REST IGNORE) NIL)
(DEFUN NOTYPE	     (&QUOTE &REST IGNORE) NIL)
(DEFUN ARRAY*	     (&QUOTE &REST IGNORE) NIL)
(DEFUN GENPREFIX     (&QUOTE &REST IGNORE) NIL)
(DEFUN MUZZLED	     (&QUOTE &REST IGNORE) NIL)
(DEFUN MAPEX	     (&QUOTE &REST IGNORE) NIL)
(DEFUN SPLITFILE     (&QUOTE &REST IGNORE) NIL)
(DEFUN EXPR-HASH     (&QUOTE &REST IGNORE) NIL)

;; Run time stuff

(DEFUN SYMBOLCONC (&REST SYMS)
  (INTERN (APPLY #'STRING-APPEND
		 (MAPCAR #'(LAMBDA (SYM)
			     (COND ((FLOATP SYM)
				    (FORMAT NIL "~S" SYM))
				   ((FIXP SYM)
				    (FORMAT NIL "~D" SYM))
				   (T SYM)))
			 SYMS))))

(DEFUN QUOTED-ARGS (&QUOTE &REST L)
  (MAPCAR #'(LAMBDA (X) (PUTPROP X '((1005 (FEF-ARG-OPT FEF-QT-QT))) 'ARGDESC))
	  L))
